conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts.views import PostListView

urlpatterns = [
    path('', PostListView.as_view()),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', PostListView.as_view(), name='list'),
    path('create/', PostCreateView.as_view(), name='create'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', PostUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='delete'),
]

posts/models.py
from django.db import models
from django.urls import reverse_lazy


class Post(models.Model):
    POST_TYPE = (
        (0, '공지사항'),
        (1, '자유게시판'),
    )
    title = models.CharField('title', max_length=50)
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    content = models.TextField('Content')
    create_date = models.DateTimeField('Create Date', auto_now_add=True)
    modify_date = models.DateTimeField('Modify Date', auto_now=True)
    type = models.PositiveSmallIntegerField('type', choices=POST_TYPE)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-modify_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('posts:detail', kwargs={'pk': self.id})

    def get_prev(self):
        return self.get_previous_by_create_date()

    def get_next(self):
        return self.get_next_by_create_date()


class PostComment(models.Model):
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    post = models.ForeignKey('posts.Post', on_delete=models.CASCADE)
    created_date = models.DateTimeField('created date', auto_now_add=True)
    content = models.TextField('content')

    class Meta:
        verbose_name = 'post comment'
        verbose_name_plural = 'post comments'
        ordering = ('-created_date',)

    def __str__(self):
        return self.content

posts/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget
from .models import Post


class PostForm(forms.ModelForm):
    type = forms.HiddenInput()

    class Meta:
        model = Post
        fields = ('title', 'content', 'type')
        widgets = {
            'content': SummernoteWidget(),
        }

posts/views.py
from django.urls import reverse_lazy
from django.views.generic import DeleteView, ListView, CreateView, UpdateView
from django.contrib import messages
from django.db.models import Q
from django.views.generic.detail import SingleObjectMixin

from .models import Post
from .forms import PostForm
# Create your views here.


class PostListView(ListView):
    model = Post
    template_name = 'posts/list.html'
    paginate_by = 5
    ordering = ('-create_date',)

    def get_queryset(self):
        queryset = super(PostListView, self).get_queryset()
        keyword = self.request.GET.get('q')

        if keyword:
            return queryset.filter(Q(title__contains=keyword) | Q(content__contains=keyword))
        else:
            return queryset


class PostDetailView(SingleObjectMixin, ListView):
    template_name = 'posts/detail.html'

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Post.objects.all())
        return super(PostDetailView, self).dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        author = request.user
        content = request.POST.get('content')
        self.object.postcomment_set.create(author=author, content=content)
        messages.info(request, '댓글이 작성되었습니다.')
        return self.get(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(PostDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.object
        return context

    def get_queryset(self):
        return self.object.postcomment_set.order_by('created_date').all()


class PostCreateView(CreateView):
    model = Post
    template_name = 'posts/create.html'
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, '게시물이 작성되었습니다.')
        return super(PostCreateView, self).get_success_url()

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(UpdateView):
    model = Post
    template_name = 'posts/update.html'
    form_class = PostForm

    def get_success_url(self):
        messages.info(self.request, '게시물이 수정되었습니다.')
        return super(PostUpdateView, self).get_success_url()


class PostDeleteView(DeleteView):
    model = Post
    success_url = reverse_lazy('posts:list')

    def get(self, request, *args, **kwargs):
        response = self.delete(request, *args, **kwargs)
        messages.info(request, '게시물이 삭제되었습니다.')
        return response

posts/templates/posts/base.html
{% extends 'base.html' %}

{% block navbar %}
    <div class="container">
        <ul class="nav nav-tabs nav-justified">
            <li role="presentation"><a href="#">소개</a></li>
            <li role="presentation" class="active"><a href="#">공지사항</a></li>
            <li role="presentation"><a href="#">자유게시판 </a></li>
        </ul>
    </div>
{% endblock navbar %}

posts/templates/posts/create.html
{%  extends "posts/base.html" %}

{% block navbar %}{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'posts:create' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">작성</button>
        </form>
    </div>
{% endblock content %}

posts/templates/posts/detail.html
{%  extends "posts/base.html" %}

{% block navbar %}{% endblock %}

{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>{{object.title}}<span class="small"> {{ object.author }} | {{ object.modify_date}}</span></h1>
                <a href="{% url 'posts:delete' pk=object.id %}">삭제하기</a>
                /<a href="{% url 'posts:update' pk=object.id %}">수정하기</a>
            </div>
            <div class="panel-body">
                <p>{{object.content|safe}}</p>
            </div>
        </div>
        {% if object_list %}
            <div class="panel panel-default">
                <div class="panel-heading">댓글</div>
                <table class="table">
                    <tbody>
                    {% for comment in object_list %}
                        <tr>
                            <td>
                                {{ comment.author }}: {{ comment.content }} ({{ comment.created_date }})
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
        <form action="{% url 'posts:detail' pk=post.id %}" method="post" accept-charset="utf-8">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" name='content' class="form-control" placeholder="댓글내용을 입력해주세요.">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">댓글달기</button>
                </span>
            </div><!-- /input-group -->
        </form>
        <nav aria-label="...">
            <ul class="pager">
                {% if object.get_prev %}
                    <li class="previous"><a href="{{ object.get_prev.get_absolute_url }}"><span aria-hidden="true">&larr;</span> 이전글</a></li>
                {% endif %}
                {% if object.get_next %}
                    <li class="next"><a href="{{ object.get_next.get_absolute_url }}">다음글 <span aria-hidden="true">&rarr;</span></a></li>
                {% endif %}
            </ul>
        </nav>
    </div>
{% endblock content %}

posts/templates/posts/list.html
{%  extends "posts/base.html" %}
{% load bootstrap_pagination %}
{% block content %}
    <div class="container" style="margin-top: 50px">
        <table class="table table-hover table-striped table-bordered">
            <thead>
            <th class="col-xs-1">번호</th>
            <th class="col-xs-5">제목</th>
            <th class="col-xs-3">작성일</th>
            <th class="col-xs-1">작성자</th>
            </thead>
            <tbody>
            {% for post in object_list %}
                <tr>
                    <td><a href="{% url 'posts:detail' pk=post.id %}">{{ post.id }}</a></td>
                    <td>{{ post.title }}</td>
                    <td>{{ post.modify_date }}</td>
                    <td>{{ post.author.username }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav aria-label="Page navigation" style="text-align: center">
            {% bootstrap_paginate page_obj range=5 show_first_last='true' show_prev_next='false'%}
        </nav>
        <a href="{% url 'posts:create' %}">새글쓰기</a>
        <form action="{% url 'posts:list' %}" method="get" accept-charset="utf-8">
            <div class="input-group">
                <input type="text" name='q' class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">검색</button>
                    </span>
            </div><!-- /input-group -->
        </form>
    </div>
{% endblock content %}

posts/templates/posts/update.html
{%  extends "posts/base.html" %}

{% block navbar %}{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{% url 'posts:update' pk=object.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">수정</button>
        </form>
    </div>
{% endblock content %}